apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.Values.storage.name}}
spec:
  capacity:
    storage: {{.Values.storage.capacity}}
  accessModes:
    - ReadWriteOnce
  storageClassName: {{.Values.storage.classname}}
  csi:
    driver: {{.Values.storage.driver}}
    fsType: ext4
    volumeHandle: {{.Values.storage.id}}
