---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ template "ui.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: {{.Values.ingress.classname}}
  tls:
    - hosts:
        - {{ .Values.ingress.tls.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ .Release.Name }}-{{ .Chart.Name }}
                port:
                  number: {{ .Values.service.externalPort }}
