version: '3.3'
services:

  post_db:
    image: mongo:${MONGO_VERSION}
    environment:
     - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    volumes:
      - post_db:/data/db
    networks:
      - back_net

  ui:
    #build: ./ui
    image: ${USERNAME}/ui:${UI_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    volumes:
      - ./ui:/app
    ports:
      - ${UI_PORT}:9292/tcp
    command: puma --debug -w 2
    depends_on:
      - post
    networks:
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post

  post:
    #build: ./post-py
    image: ${USERNAME}/post:${POST_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    volumes:
      - ./post-py:/app
    networks:
      - back_net
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post

  comment:
    #build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    volumes:
      - ./comment:/app
    command: puma --debug -w 2
    networks:
      - back_net
      - front_net


  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - back_net
      - front_net

  node-exporter:
    image: prom/node-exporter:latest
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    ports:
      - "9100:9100"
    networks:
      - back_net
      - front_net

  mongo-exporter:
    image: percona/mongodb_exporter:0.40
    command:
      - '--mongodb.uri=mongodb://post_db:27017'
      - '--collect-all'
    ports:
      - '9216:9216'
    networks:
      - back_net

  blackbox-exporter:
#    image: quay.io/prometheus/blackbox-exporter:v0.25.0
     image: ${USERNAME}/blackbox-exporter
     ports:
       - '9115:9115'
     networks:
       - front_net
       - back_net



volumes:
  post_db:
  prometheus_data:

networks:
  front_net:
  back_net:
  reddit:
